---
title: "Multidimensional scaling of similarity data"
author: "Monica Kullar"
date: "10/1/2021"
output: html_document
---
#data setup
```{r}
distance <- read.table("~/readfile.txt", sep = "\t", header = TRUE)
short <- c("Subject", "Comp1", "Comp2", "Distance")
distance <- distance[short]

#there seems to be one NA of a null row per person, confirm
34950-75
#34875
distance <- na.omit(distance) #perfect
sapply(distance, class)
distance$Subject <- as.factor(distance$Subject)
distance$Comp1 <- as.factor(distance$Comp1)
distance$Comp2 <- as.factor(distance$Comp2)

levels(distance$Comp2)
posSPAMmood <- c("CALM", "CAREFREE", "CHEERFUL", "COMPOSED", "CONTENT", "EXCITED", "HAPPY", "JOYFUL", "LIVELY", "MANIC", "OPTIMISTIC", "PASSIONATE", "RELAXED", "SATISFIED", "SERENE")
negSPAMmood <- c("ANXIOUS", "BITTER", "BORED",  "DEPRESSED", "DESPERATE", "FED UP", "GLOOMY", "GUILTY", "IRRITABLE", "MISERABLE", "PANICKY", "PESSIMISTIC", "SAD", "STRESSED", "TENSE", "UNEASY")

library(tidyverse)
distance <- distance %>% 
  rename_with(.cols = 1, ~"PtcptID")

#I now have pairwise similarity for all terms across all participants.
#lets do a quick group check?
distancetest <- merge(distance, test0dem[,c(1,6)], by= "PtcptID")
32085/69 # ihave the right amount of 69 participants!
465*75 #perfect, correct amount of total rows based on 465 pairwise combos per person
#single pairwise variable for comparisons?
distancetest$termpairs <- paste(distancetest$Comp1, distancetest$Comp2, sep= "-")

library(dplyr)
distancetestsummary <- distancetest %>% group_by(Group, termpairs) %>%
    summarise(Mean = mean(Distance))

#ggplot(distancetestsummary, aes(x=Mean, y=termpairs, group=Group)) + geom_point() #just to quickly look

    # REMOVE BORED (outlier term): determined after all subsequent analyses. here for completion and transparency.
distancetest <- distancetest[!grepl("BORED", distancetest$Comp1),]
distancetest <- distancetest[!grepl("BORED", distancetest$Comp2),]
```

# Loops for individual matrices, individual configuration plots
```{r}
library(data.table)
library(dplyr)
library(reshape2)
library(smacof)
library(magrittr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggrepel)

rownames(distancetest) <- 1:nrow(distancetest)

# INDIVIDUAL MATRIX CREAITON LOOP
for(i in levels(test0dem$PtcptID)) { #use from demographics script in order to get true N=69 levels saved.
    #single out an individual participant
    matrixloop1 <- distancetest[distancetest$PtcptID == i,]
    an <- with(matrixloop1[,2:4], sort(unique(c(as.character(Comp1), as.character(Comp2)))))
    SpamMatrixtemp <- array(0, c(length(an), length(an)), list(an, an))
    a <- match(matrixloop1[,2:4]$Comp1, an)
    b <- match(matrixloop1[,2:4]$Comp2, an)
    SpamMatrixtemp[cbind(a,b)] <- SpamMatrixtemp[cbind(b,a)] <- matrixloop1[,2:4]$Distance
    #save all files in Imp folder for use at individual level
    savefile <- paste0 ("~/output/indivmatrices/", i, ".csv", sep = "")
    write.csv(SpamMatrixtemp, file = savefile, row.names = TRUE)
    #print output into console to see status
    print(paste("Dataframe Saved:", i))
    #save outputs to location with unique name match.
}

# INDIVIDUAL GGSCATTER CONFIGURATION PLOT CREATION LOOP
for(i in levels(test0dem$PtcptID)) { #use from demographics script in order to get true N=69 levels saved.
    #single out an individual participant
    matrixloop1 <- distancetest[distancetest$PtcptID == i,]
    an <- with(matrixloop1[,2:4], sort(unique(c(as.character(Comp1), as.character(Comp2)))))
    SpamMatrixtemp <- array(0, c(length(an), length(an)), list(an, an))
    a <- match(matrixloop1[,2:4]$Comp1, an)
    b <- match(matrixloop1[,2:4]$Comp2, an)
    SpamMatrixtemp[cbind(a,b)] <- SpamMatrixtemp[cbind(b,a)] <- matrixloop1[,2:4]$Distance
    #create their mds plot
    spam_mdstemp <-  mds(delta = SpamMatrixtemp, ndim = 2, type = "ordinal")
  #simple clean readable config plot
  plottemp <- ggplot() + geom_point(data = as.data.frame(spam_mdstemp$conf), 
                      mapping = aes(x = D1 , y = D2), 
                      alpha = 0.5 , color = "blue", size = 3) + 
  geom_text_repel(data = as.data.frame(spam_mdstemp$conf), 
            mapping = aes(x = D1,y= D2), 
            label = rownames(SpamMatrixtemp)) + 
  labs(title = "MDS representation of Mood") + xlab("Dimension 1") + ylab ("Dimension 2") +
  theme_classic()

    #save all files in Imp folder for use at individual level
    savefile <- paste0 (i, ".jpg", sep = "")
    ggsave(file=savefile, plot=plottemp, path = "~/output/indivmatrices/indivconfigplots_NoBored/")
    #print output into console to see status
    print(paste("Dataframe Saved:", i))
    #save outputs to location with unique name match.
}
```


# Average Low and High Risk Group analysis of matrices (averaging matrices, stress, plots, variance diff)
```{r}
library(data.table)
library(dplyr)
library(reshape2)
library(smacof)
library(magrittr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(stats)

#Average matrices for low and high risk groups by SUBFOLDER OF PRESORTED GROUPS.
    ## LOW RISK ##
#pull all the csv files from the subfolder
filenamesLR <- list.files(path ="~/output/indivmatrices/lowrisk_noBored", pattern="*.csv", full.names=TRUE)
#read them in as csv, then as matrices which is what i want
ldfLR <- lapply(filenamesLR, read.csv)
resLR <- lapply(ldfLR, as.matrix)
#make each one have their mood terms as row names via lapply.
resLR <- lapply(ldfLR, function(df) {
    #new df without rowname col
    df_out <- df[,-1]
    #set rownames as first col from input df
    rownames(df_out) <- df[[1]]
    df_out
})
#matrix average LOW RISK
AvgMatrixLoRisk <- Reduce(`+`, resLR)/length(resLR)

    ## HIGH RISK ##
filenamesHR <- list.files(path ="~/output/indivmatrices/highrisk_noBored", pattern="*.csv", full.names=TRUE)
ldfHR <- lapply(filenamesHR, read.csv)
resHR <- lapply(ldfHR, as.matrix)
#make each one have their mood terms as row names via lapply.
resHR <- lapply(ldfHR, function(df) {
    #new df without rowname col
    df_out <- df[,-1]
    #set rownames as first col from input df
    rownames(df_out) <- df[[1]]
    df_out
})
AvgMatrixHiRisk <- Reduce(`+`, resHR)/length(resHR)

#Assess group matrices 
#analyze configuration plots, stress values, normalized stress, and k-means clustering of outputs.

#Low Risk
spam_mdsLR <-  mds(delta = AvgMatrixLoRisk, ndim = 2, type = "ratio" )
spam_mdsLR
spam_mdsLR$stress #the stress value = .13 GREAT
dhat_matrix <-  as.matrix(spam_mdsLR$dhat)
d_matrix <-  as.matrix(spam_mdsLR$confdist)
denominator <-  sum(dhat_matrix[upper.tri(dhat_matrix)]^2)
p_ij <-  dhat_matrix[upper.tri(dhat_matrix)]
d_ij <-  d_matrix[upper.tri(d_matrix)]
nominator <-  sum((p_ij - d_ij)^2) 
normalized_stressLR  <-  nominator/denominator
normalized_stressLR #the normalized stress value = 0.02 GREAT

#High Risk
spam_mdsHR <-  mds(delta = AvgMatrixHiRisk, ndim = 2, type = "ratio" )
spam_mdsHR
spam_mdsHR$stress #the stress value = .13 GREAT
dhat_matrix <-  as.matrix(spam_mdsHR$dhat)
d_matrix <-  as.matrix(spam_mdsHR$confdist)
denominator <-  sum(dhat_matrix[upper.tri(dhat_matrix)]^2)
p_ij <-  dhat_matrix[upper.tri(dhat_matrix)]
d_ij <-  d_matrix[upper.tri(d_matrix)]
nominator <-  sum((p_ij - d_ij)^2) 
normalized_stressHR  <-  nominator/denominator
normalized_stressHR #the normalized stress value = 0.02 GREAT

#compare spread of both dimensions.
LRscores <- as.data.frame(spam_mdsLR$conf)
mean(LRscores$D1)
sd(LRscores$D1)
mean(LRscores$D2)
sd(LRscores$D2)

MoodLRscores <- LRscores

HRscores <- as.data.frame(spam_mdsHR$conf)
mean(HRscores$D1)
sd(HRscores$D1)
mean(HRscores$D2)
sd(HRscores$D2)

MoodHRscores <- HRscores

#Group plots by risk status
plot(spam_mdsLR)
plot(spam_mdsHR)
#Low risk
LRplot <- ggplot() + geom_point(data = as.data.frame(spam_mdsLR$conf), 
                      mapping = aes(x = D1 , y = D2), 
                      alpha = 0.5 , color = "blue", size = 3) + 
  geom_text_repel(data = as.data.frame(spam_mdsLR$conf), 
            mapping = aes(x = D1,y= D2), 
            label = rownames(AvgMatrixLoRisk)) + 
  labs(title = "MDS representation of Mood: Low Risk Group") + xlab("Dimension 1") + ylab ("Dimension 2") +
  theme_classic()
    ggsave(file="LRplotnoBoredRatio.jpg", plot=LRplot, path = "~/output/")
#high risk
HRplot <- ggplot() + geom_point(data = as.data.frame(spam_mdsHR$conf), 
                      mapping = aes(x = D1 , y = D2), 
                      alpha = 0.5 , color = "blue", size = 3) + 
  geom_text_repel(data = as.data.frame(spam_mdsHR$conf), 
            mapping = aes(x = D1,y= D2), 
            label = rownames(AvgMatrixHiRisk)) + 
  labs(title = "MDS representation of Mood: High Risk Group") + xlab("Dimension 1") + ylab ("Dimension 2") +
  theme_classic()
  #scale_y_continuous(limits = c(-.5, .4)) #make same as low risk plot Y (X is already same)
    ggsave(file="HRplotnoBoredRatio.jpg", plot=HRplot, path = "~/output/")

LRscores$Group <- "LowRisk"
HRscores$Group <- "HighRisk"

LRHR <- rbind(LRscores, HRscores)
#plot the spread
#boxplot(D2 ~ Group, data = LRHR)
ggplot(LRHR, aes(x=Group, y=D1, fill=Group)) + geom_boxplot() + ggtitle("Spread of Dimension 1 between Groups") +
  theme_classic()
ggplot(LRHR, aes(x=Group, y=D2, fill=Group)) + geom_boxplot() + ggtitle("Spread of Dimension 2 between Groups") +
  theme_classic()


# STATISTIC FOR CHECKING OUTLIERS
checkingoutliers <- as.data.frame(spam_mdsLR$conf)
#get Z-value for the D2 variables.
checkingoutliers$z_scores <- (checkingoutliers$D2-mean(checkingoutliers$D2))/sd(checkingoutliers$D2)
z_scores

checkingoutliers <- as.data.frame(spam_mdsHR$conf)
#get Z-value for the D2 variables.
checkingoutliers$z_scores <- (checkingoutliers$D2-mean(checkingoutliers$D2))/sd(checkingoutliers$D2)
z_scores

```

#Clustering attempts, difference in groups
```{r}
library(stats)
library(dplyr)
library(ggplot2)
library(ggpubr)
mdsLR <- spam_mdsLR$conf
mdsHR <- spam_mdsHR$conf

# Determine number of clusters
wss <- (nrow(mdsLR)-1)*sum(apply(mdsLR,2,var))
for (i in 2:15) wss[i] <- sum(kmeans(mdsLR,
   centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters",
  ylab="Within groups sum of squares", main ="Low Risk Group") #strongly 2

wss <- (nrow(mdsHR)-1)*sum(apply(mdsHR,2,var))
for (i in 2:15) wss[i] <- sum(kmeans(mdsHR,
   centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters",
  ylab="Within groups sum of squares", main ="High Risk Group") #also strongly 2

# Ward Hierarchical Clustering
d <- dist(mdsLR, method = "euclidean") # distance matrix
fit <- hclust(d, method="ward")
plot(fit) # display dendogram
groups <- cutree(fit, k=4) # cut tree into N clusters
# draw dendogram with red borders around the N clusters
rect.hclust(fit, k=2, border="blue")
rect.hclust(fit, k=4, border="red")

d <- dist(mdsHR, method = "euclidean")
fit <- hclust(d, method="ward")
plot(fit)
groups <- cutree(fit, k=4)
rect.hclust(fit, k=2, border="blue")
rect.hclust(fit, k=4, border="red")

#number of clusters to attempt
N <- 2
#Clustering LOW RISK
clust <- kmeans(mdsLR, N)$cluster %>%
  as.factor()
mdsLR <- mdsLR %>%
  mutate(groups = clust)

ggplot() + geom_point(data = as.data.frame(spam_mdsLR$conf), 
                      mapping = aes(x = D1 , y = D2), 
                      alpha = 0.5 , color = "blue", size = 3) + 
  geom_text_repel(data = as.data.frame(spam_mdsLR$conf), 
            mapping = aes(x = D1,y= D2), 
            label = rownames(AvgMatrixLoRisk)) + 
  labs(title = "MDS representation of Mood: Low Risk Group") + xlab("Dimension 1") + ylab ("Dimension 2") +
  theme_classic() +
  geom_polygon(data = mdsLR,
               aes(fill = groups,
                   colour = groups),
               alpha = 0.3,
               show.legend = FALSE)
    
ggplot() + geom_point(data = as.data.frame(spam_mdsHR$conf), 
                      mapping = aes(x = D1 , y = D2), 
                      alpha = 0.5 , color = "blue", size = 3) + 
  geom_text_repel(data = as.data.frame(spam_mdsHR$conf), 
            mapping = aes(x = D1,y= D2), 
            label = rownames(AvgMatrixHiRisk)) + 
  labs(title = "MDS representation of Mood: High Risk Group") + xlab("Dimension 1") + ylab ("Dimension 2") +
  theme_classic() +
  scale_y_continuous(limits = c(-.5, .4)) #make same as low risk plot Y (X is already same)




# Plot and color by groups
ggscatter(mdsLR, x = "V1", y = "V2", 
          label = rownames(SpamMatrix),
          color = "groups",
          palette = "jco",
          size = 1, 
          ellipse = TRUE,
          ellipse.type = "convex",
          repel = TRUE) + theme_classic() + ggtitle("Low Risk Group")

#Clustering HIGH RISK
clust <- kmeans(mdsHR, N)$cluster %>%
  as.factor()
mdsHR <- mdsHR %>%
  mutate(groups = clust)
# Plot and color by groups
ggscatter(mdsHR, x = "V1", y = "V2", 
          label = rownames(SpamMatrix),
          color = "groups",
          palette = "jco",
          size = 1, 
          ellipse = TRUE,
          ellipse.type = "convex",
          repel = TRUE) + theme_classic() + ggtitle("High Risk Group")


# check difference between matrices
diffMds <- mdsHR$conf - mdsLR$conf
sapply(diffMds, class)
#plot
ggscatter(as.data.frame(diffMds), x = "D1", y = "D2", 
          label = rownames(diffMds),
          palette = "jco",
          size = 1,
          repel = TRUE) + theme_classic() + ggtitle("Distance Differences (HR-LR)") +
          geom_vline(xintercept=0, col="red") +
          geom_hline(yintercept=0, col="blue")


```

#single sample MDS
```{r}
#notes are above, this is code and simple/clean only for the whole sample collapsed.

#Average matrix
filenamesFULL <- list.files(path ="~/output/indivmatrices", pattern="*.csv", full.names=TRUE)
ldfFULL <- lapply(filenamesFULL, read.csv)
resFULL <- lapply(ldfFULL, as.matrix)
resFULL <- lapply(ldfFULL, function(df) {
    df_out <- df[,-1]
    rownames(df_out) <- df[[1]]
    df_out
})
AvgMatrixFULL <- Reduce(`+`, resFULL)/length(resFULL)

#Stress and normalized stress
spam_mdsFULL <-  mds(delta = AvgMatrixFULL, ndim = 2, type = "ordinal" )
spam_mdsFULL
spam_mdsFULL$stress #the stress value = .05 GREAT
dhat_matrix <-  as.matrix(spam_mdsFULL$dhat)
d_matrix <-  as.matrix(spam_mdsFULL$confdist)
denominator <-  sum(dhat_matrix[upper.tri(dhat_matrix)]^2)
p_ij <-  dhat_matrix[upper.tri(dhat_matrix)]
d_ij <-  d_matrix[upper.tri(d_matrix)]
nominator <-  sum((p_ij - d_ij)^2) 
normalized_stressFULL  <-  nominator/denominator
normalized_stressFULL #the normalized stress value = .003 GREAT

#Plot
Fullplot <- ggplot() + geom_point(data = as.data.frame(spam_mdsFULL$conf), 
                      mapping = aes(x = D1 , y = D2), 
                      alpha = 0.5 , color = "blue", size = 3) + 
  geom_text_repel(data = as.data.frame(spam_mdsFULL$conf), 
            mapping = aes(x = D1,y= D2), 
            label = rownames(AvgMatrixLoRisk)) + 
  labs(title = "MDS representation of Mood: Whole Sample") + xlab("Dimension 1") + ylab ("Dimension 2") +
  theme_classic() +
  scale_y_continuous(limits = c(-.5, .4)) #make same as low risk plot Y (X is already same)
    ggsave(file="Fullplot.jpg", plot=Fullplot, path = "~/output/")

```